app/tgc/urls.py
from django.urls import path

from . import views

app_name = 'tgc'
urlpatterns = [
    path('', views.index, name='index'),

    path('users/<int:user_id>/<str:public_key>/', views.user_home, name='user_home'),
    path('users/<int:user_id>/<str:public_key>/all-cards/', views.user_all_cards, name='user_all_cards'),
    path('users/<int:user_id>/<str:public_key>/collections/', views.user_collections, name='user_collections'),
    path('users/<int:user_id>/<str:public_key>/collections/<int:collection_id>/', views.user_collection_detail,
         name='user_collection_detail'),

    path('add-cards/', views.add_cards, name='add_cards'),
    path('add-cards/collection/<int:collection_id>', views.add_cards_to_collection, name='add_cards_to_collection'),

    path('cards/<int:user_id>/<str:public_key>', views.legacy_redirect_cards),

    path('api/collections/create/', views.create_collection, name='create_collection'),
    path('api/collections/edit/', views.edit_collection, name='edit_collection'),
    path('api/collections/delete/', views.delete_collection, name='delete_collection'),
    path('api/collections/delete-card', views.delete_card_in_collection, name='delete_card_in_collection'),
    path('api/move-from-collection', views.move_cards_from_to_collection, name='move_cards_from_to_collection'),
    path('api/move-card', views.move_card_to_collection, name='move_card_to_collection'),
    path('api/edit-card', views.edit_card, name='edit_card'),

    # TODO export just one collection + my_cards update
    path('api/export-cards-xlsx/<int:user_id>/<str:public_key>', views.export_cards_xlsx, name='export_cards_xlsx'),

    path('rest/add-to-collection/', views.add_to_collection, name='rest_add_to_collection'),

    path('rest/get-user-cards/<int:user_id>/<str:public_key>/', views.get_user_cards, name='rest_get_user_cards'),
    path('rest/get-collection-cards/<int:user_id>/<str:public_key>/<int:collection_id>/', views.get_collection_cards,
         name='rest_get_collection_cards'),
]

app/tgc/models.py
import random
import string

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.functions import Lower
from django.db.models.signals import post_save
from django.dispatch import receiver


COLLECTION_TYPE_CHOICES = (
    ('binder', 'Binder'),
    ('deck', 'Deck'),
)


class SetEdition(models.Model):
    """
    A single MTG set.

    User agnostic.
    """
    scryfall_id = models.UUIDField(
        unique=True,
    )

    code = models.CharField(
        max_length=128,
    )
    name = models.CharField(
        max_length=128,
    )
    released_at = models.CharField(
        max_length=10,
    )

    icon_svg_uri = models.URLField()


class Card(models.Model):
    """
    A single card, without any set/quality/quantity/language specification.

    Eg. a card can be 'Swords to Plowshares', but not an 'Ice Age NM Swords to Plowshares'.

    It's effectively a another of grouping of cards. If you want to know, how many Llanowar Elves you have, you go to
    this class. Then you ask in what binders those are.

    Note that Cards are actually user independent. They define only what cards exist -- then it's up to user to say
    what does he have in his collection.
    """

    name = models.CharField(
        max_length=128,
    )

    oracle_id = models.UUIDField()

    mana_cost = models.CharField(
        max_length=128
    )

    cmc = models.FloatField()

    type = models.CharField(
        max_length=128,
    )

    power = models.CharField(
        max_length=4,
        null=True,
    )

    toughness = models.CharField(
        max_length=4,
        null=True,
    )

    card_json = models.TextField()


class CardPrint(models.Model):
    """
    A concrete card print, with a set definition, possible language (if implemented).

    Pretty close to Scryfalls' `card` object.

    Does not hold quantity or quality (or ownership) information.

    User agnostic.
    """

    set_edition = models.ForeignKey(
        SetEdition,
        on_delete=models.RESTRICT,
    )

    card = models.ForeignKey(
        Card,
        on_delete=models.RESTRICT,
    )

    printed_name = models.CharField(
        max_length=128,
        null=True,
    )

    lang = models.CharField(
        max_length=32,
        null=True,
    )

    released_at = models.CharField(
        max_length=10,
    )

    scryfall_id = models.UUIDField(
        unique=True
    )

    card_json = models.TextField()

    image_uri_large = models.URLField(
        null=True,
    )
    image_uri_normal = models.URLField(
        null=True,
    )
    image_uri_small = models.URLField(
        null=True,
    )
    image_uri_art_crop = models.URLField(
        null=True,
    )
    scryfall_uri = models.URLField(
        null=True,
    )


class Collection(models.Model):
    """
    Collection is binder, deck, an arbitrary grouping container for cards.
    """

    name = models.CharField(
        max_length=128,
    )

    note = models.CharField(
        max_length=128,
        default='',
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    type = models.CharField(
        max_length=16,
        choices=COLLECTION_TYPE_CHOICES,
        default=COLLECTION_TYPE_CHOICES[0][0]
    )

    def __str__(self):
        return 'Collection %s' % self.name

    class Meta:
        ordering = ['type', Lower('name'), ]


class CardInCollection(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    note = models.CharField(
        max_length=128,
        default='',
    )

    card_print = models.ForeignKey(
        CardPrint,
        on_delete=models.RESTRICT,
    )

    collection = models.ForeignKey(
        Collection,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    count = models.PositiveSmallIntegerField()

    foil = models.BooleanField(
        default=False,
    )


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    public_link_key = models.CharField(
        max_length=8,
    )

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.public_link_key:
            self.public_link_key = ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))

        super().save(force_insert, force_update, using, update_fields)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)

app/tgc/views.py
import csv
import io
import json

import xlsxwriter
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST, require_GET

from tgc.models import Collection, CardInCollection
from tgc.scryfall import get_or_create_card_print


def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('tgc:user_home', kwargs={
            'user_id': request.user.id,
            'public_key': request.user.userprofile.public_link_key,
        }))

    return render(request, 'tgc/index.html')


@login_required
def add_cards(request):
    # TODO complete cleanup / refactoring of this file
    return render(request, 'tgc/add_cards.html', {
        'collections': Collection.objects.filter(user=request.user).all()
    })


@login_required
def add_cards_to_collection(request, collection_id):
    return render(request, 'tgc/add_cards.html', {
        'collections': Collection.objects.filter(user=request.user).all(),
        'selected_collection_id': collection_id,
    })


def legacy_redirect_cards(request, user_id: int, public_key: str):
    user = get_object_or_404(User, id=user_id, userprofile__public_link_key=public_key)

    return redirect(reverse('tgc:user_all_cards', kwargs={
        'user_id': user.id,
        'public_key': user.userprofile.public_link_key,
    }))


def user_home(request, user_id: int, public_key: str):
    user = get_object_or_404(User, id=user_id, userprofile__public_link_key=public_key)

    collection_counts = {
        csum['collection_id']: csum['count__sum'] for csum in
        CardInCollection.objects.filter(collection__user=user).values('collection_id').annotate(Sum('count'))
    }

    collections = list(
        (c, collection_counts.get(c.id, 0)) for c in
        Collection.objects.filter(user=user).select_related('user__userprofile').all()
    )

    return render(request, 'tgc/user_home.html', {
        'owner': user,
        'is_owner': user == request.user,
        'collections': collections,
    })


def user_all_cards(request, user_id: int, public_key: str):
    user = get_object_or_404(User, id=user_id, userprofile__public_link_key=public_key)
    is_owner = user == request.user
    collections = []
    if is_owner:
        collections = Collection.objects.filter(user=user.id).all()

    return render(request, 'tgc/cards.html', {
        'owner': user,
        'is_owner': is_owner,
        'collections': collections,
    })


def user_collections(request, user_id: int, public_key: str):
    user = get_object_or_404(User, id=user_id, userprofile__public_link_key=public_key)

    collection_counts = {
        csum['collection_id']: csum['count__sum'] for csum in
        CardInCollection.objects.filter(collection__user=user).values('collection_id').annotate(Sum('count'))
    }

    collections = list(
        (c, collection_counts.get(c.id, 0)) for c in
        Collection.objects.filter(user=user).select_related('user__userprofile').all()
    )

    return render(request, 'tgc/collections.html', {
        'owner': user,
        'is_owner': user == request.user,
        'collections': collections,
    })


def user_collection_detail(request, user_id: int, public_key: str, collection_id: int):
    user = get_object_or_404(User, id=user_id, userprofile__public_link_key=public_key)
    collection = get_object_or_404(Collection, user=user, id=collection_id)
    is_owner = user == request.user
    collections = []
    if is_owner:
        collections = Collection.objects.filter(user=user.id).all()

    return render(request, 'tgc/cards.html', {
        'collection': collection,
        'owner': user,
        'is_owner': is_owner,
        'collections': collections,
    })


@login_required
@require_POST
def create_collection(request):
    collection = Collection(
        name=request.POST['name'],
        note=request.POST['note'],
        type=request.POST['type'],
        user=request.user
    )
    collection.save()

    messages.add_message(request, messages.SUCCESS, 'Binder / Deck %s created.' % collection.name)
    return redirect(request.POST['next'])


@login_required
@require_POST
def edit_collection(request):
    collection = get_object_or_404(Collection, user=request.user, id=request.POST['id'])

    collection.name = request.POST['name']
    collection.note = request.POST['note']
    collection.type = request.POST['type']
    collection.save()

    messages.add_message(request, messages.SUCCESS, 'Binder / Deck %s updated.' % collection.name)
    return redirect(request.POST['next'])


@login_required
@require_POST
def delete_collection(request):
    collection = get_object_or_404(Collection, user=request.user, id=request.POST['id'])

    if len(collection.cardincollection_set.all()) > 0:
        messages.add_message(request, messages.ERROR,
                             'Binder / Deck %s has cards in it, cannot be deleted.' % collection.name)

    else:
        collection.delete()
        messages.add_message(request, messages.SUCCESS, 'Binder / Deck %s deleted.' % collection.name)

    return redirect(request.POST['next'])


@login_required
@require_POST
def move_cards_from_to_collection(request):
    collection = get_object_or_404(Collection, user=request.user, id=request.POST['collection-id'])

    moved_ids = list(x[0][len('card_move_'):] for x in request.POST.items() if x[0].startswith('card_move_'))

    for id in moved_ids:
        cic = CardInCollection.objects.select_related('collection').filter(collection__user=request.user, id=id).get()
        count = int(request.POST['card_count_%s' % id])

        move_single_card_to_collection(cic, count, collection)

    messages.add_message(request, messages.SUCCESS, 'Cards moved.')

    return redirect(request.POST['next'])


@login_required
@require_POST
def move_card_to_collection(request):
    collection = get_object_or_404(Collection, user=request.user, id=request.POST['collection-id'])

    cic = CardInCollection.objects.select_related('collection').filter(collection__user=request.user,
                                                                       id=request.POST['id']).get()
    count = int(request.POST['count'])

    move_single_card_to_collection(cic, count, collection)

    messages.add_message(request, messages.SUCCESS, 'Cards moved.')

    return redirect(request.POST['next'])


@login_required
@require_POST
def edit_card(request):
    cic = get_object_or_404(CardInCollection, collection__user=request.user, id=request.POST['id'])

    cic.count = int(request.POST['count'])
    cic.note = request.POST.get('note')

    cic.save()

    messages.add_message(request, messages.SUCCESS, 'Card %s updated, count %dx, note "%s".' % (
        cic.card_print.card.name, cic.count, cic.note
    ))

    return redirect(request.POST['next'])


def export_cards_xlsx(request, user_id: int, public_key: str):
    qs = CardInCollection.objects.filter(collection__user_id=user_id,
                                         collection__user__userprofile__public_link_key=public_key) \
        .select_related('collection', 'card_print', 'card_print__card', 'card_print__set_edition') \
        .order_by('card_print__card__name', 'card_print__released_at', 'collection_id').all()

    if request.GET.get('format') == 'dragonshield':
        output = io.BytesIO()
        wrapper = io.TextIOWrapper(output, encoding='utf-8', line_buffering=True)

        writer = csv.writer(wrapper, delimiter=',', quoting=csv.QUOTE_MINIMAL)

        writer.writerow([
            'Folder Name', 'Quantity', 'Trade Quantity', 'Card Name', 'Set Code', 'Set Name',
            'Card Number', 'Condition', 'Printing', 'Language', 'Price Bought', 'Date Bought'
        ])
        for cic in qs:
            card_json = json.loads(cic.card_print.card_json)
            card_lang_name = {
                'en': 'English',
                'es': 'Spanish',
                'fr': 'French',
                'de': 'German',
                'it': 'Italian',
                'pt': 'Portuguese',
                'ja': 'Japanese',
                'ko': 'Korean',
                'ru': 'Russian',
                'zhs': 'Simplified Chinese',
                'zht': 'Traditional Chinese',
                'he': 'Hebrew',
                'la': 'Latin',
                'grc': 'Ancient Greek',
                'ar': 'Arabic',
                'sa': 'Sanskrit',
                'ph': 'Phyrexian',
            }[cic.card_print.lang]

            writer.writerow([
                cic.collection.name,
                cic.count,
                0,
                cic.card_print.card.name,
                cic.card_print.set_edition.code,
                cic.card_print.set_edition.name,
                card_json.get('collector_number'),
                'Good',
                'Foil' if cic.foil else 'Normal',
                card_lang_name,
                '0.0',
                cic.created_at.strftime('%m/%d/%Y'),
            ])

        output.seek(0)

        filename = 'magic-collection-export.csv'
        response = HttpResponse(
            output,
            content_type='text/csv'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

    else:

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet()

        header = ['Count', 'Card', 'Lang', 'Localized Name', 'Type', 'P/T', 'Cost', 'Set', 'Note', 'Binder / Deck']
        for col_num, col in enumerate(header):
            worksheet.write(0, col_num, col)

        row_num = 1
        for cic in qs:
            worksheet.write(row_num, 0, cic.count)
            worksheet.write(row_num, 1, cic.card_print.card.name)

app/tgc/templates/tgc/index.html
{% extends 'tgc/layout.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h2 class="display-2">Welcome to Magic Collection</h2>

    <p>
        You can easily track collection of your MtG cards and possibly share with friends.
    </p>

    <p>
        <a href="{% url 'account_login' %}">Login / Register</a> first to start tracking.
    </p>

    <p>
        Once you register, you can add your collections (binders, decks) and cards to them.
    </p>

    <p>
        If you wish to, you can share your library with friends -- so that they know which cards you own and can borrow
        from you.
    </p>
{% endblock %}

app/tgc/templates/tgc/layout.html
{% load static %}<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MC | {% block title %}{% endblock %}</title>

    <link rel="icon" type="image/svg+xml" href="{% static 'image/vis.svg' %}">
    <link rel="alternate icon" href="{% static 'image/vis.svg' %}">
    <link rel="mask-icon" href="{% static 'image/vis.svg' %}" color="#ff8a01">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet"/>
    <link href="{% static 'css/tgc.css' %}" rel="stylesheet">
    <link href="{% static 'css/flag-icon.css' %}" rel="stylesheet">

</head>
<body>
<main>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'tgc:index' %}">Magic Collection</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar">
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'tgc:user_all_cards' user_id=user.id public_key=user.userprofile.public_link_key %}">
                                    All My Cards <i class="bi bi-collection"></i>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"
                                   href="{% url 'tgc:user_collections' user_id=user.id public_key=user.userprofile.public_link_key %}">
                                    My Binders &amp; Decks <i class="bi bi-journals"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'tgc:user_collections' user_id=user.id public_key=user.userprofile.public_link_key %}">
                                            Manage <i class="bi bi-tools"></i>
                                        </a>
                                    </li>
                                    {% for collection in user.collection_set.all %}
                                        {% ifchanged collection.type %}
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                        {% endifchanged %}
                                        <li>
                                            <a class="dropdown-item" href="{% url 'tgc:user_collection_detail' user_id=user.id public_key=user.userprofile.public_link_key collection_id=collection.id %}">{{ collection.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'tgc:add_cards' %}">
                                    Add Cards <i class="bi bi-file-plus"></i>
                                </a>
                            </li>
                        </ul>
                        <form method="post" action="{% url 'account_logout' %}" id="logout-form">
                            {% csrf_token %}
                            <span class="navbar-text">
                            <a class="nav-link" href="{% url 'account_logout' %}"
                               onclick="$('#logout-form').submit(); return false;">
                                Logout
                            </a>
                        </span>
                        </form>
                    {% else %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
                        <span class="navbar-text">
                            <a class="nav-link" href="{% url 'account_login' %}">
                                Login / Signup
                            </a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% block breadcrumbs %}{% endblock %}

        {% if messages %}
            <div class="alerts mt-3">

                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}

                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}
        {% endblock %}

        <footer class="pt-5 my-5 text-muted">
            Created by Savannah &copy; 2021&mdash;2022
        </footer>
    </div>
</main>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"
        integrity="sha256-qXBd/EfAdjOA2FGrGAG+b3YBn2tn5A6bhz+LSgYD96k=" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

app/tgc/templates/tgc/user_home.html
{% extends 'tgc/layout.html' %}
{% load static %}
{% load tgc_filters %}

{% block title %}{{ owner.get_full_name }}{% endblock %}

{% block breadcrumbs %}
    {% comment %}TODO possibru remove?{% endcomment %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">{{ owner.get_full_name }}</li>
        </ol>
    </nav>
{% endblock %}

{% block content %}
    <h2 class="display-2">{{ owner.get_full_name }}</h2>

    <p>
        <a href="{% url 'tgc:user_all_cards' user_id=owner.id public_key=owner.userprofile.public_link_key %}">
            <i class="bi bi-chevron-double-right"></i> Whole collection (can take a while to load...)
        </a>
    </p>

    <h3>
        Binders &amp; Decks
    </h3>
    {% if is_owner %}
        <a href="{% url 'tgc:user_collections' user_id=owner.id public_key=owner.userprofile.public_link_key %}">
            <i class="bi bi-chevron-double-right"></i> Manage <i class="bi bi-tools"></i>
        </a>
    {% endif %}

    <table id="card-list" class="cards-list table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Note</th>
            <th scope="col">Cards</th>
        </tr>
        </thead>
        <tbody>

        {% for collection, count in collections %}
            {% ifchanged collection.type %}
                <tr class="table-light text-center">
                    <th colspan="{% if is_owner %}4{% else %}3{% endif %}">{{ collection|collection_type_plural }}</th>
                </tr>
            {% endifchanged %}
            <tr>
                <td>
                    <a href="{% url 'tgc:user_collection_detail' user_id=owner.id public_key=owner.userprofile.public_link_key collection_id=collection.id %}">{{ collection.name }}</a>
                </td>
                <td>
                    {{ collection.note }}
                </td>
                <td>
                    {{ count }}x
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}